### ISSUE TITLE
24-bit addressing support

### ISSUE THREAD

**Issue by autc04** [autc04/executor#12]
Originally, Macs used 24-bit addressing. Apple introduced 32-bit addressing as an option with System 7 on 68020 and later processors, and made it mandatory some time later. This caused compatibility problems for quite a few applications.
Executor only implements 32-bit addressing and shows a warning for applications that are not explicitly marked as 32-bit compatible by their developers.

Background: The original 68000 processor ignored the upper 8 bits of every 32-bit address. Some programs took advantage of that and stored other information there, others even relied on the Memory Manager storing some information there in some situations.

TODO:
- implement a 24-bit address mapping mode for syn68k
- make sure that executor's memory use "fits" in 4 * 4MB
- make the memory manager store its attribute bits where old apps expect them

Affected Apps (that are known to crash for *this* reason):
- Turbo Pascal 1.0

**Comment by MaddTheSane** [comment]
To my knowledge, PowerPC never implemented 24-bit addressing, so if it ends up being a launch-time switch, perhaps disabling PowerPC code translation could speed some things up.

**Comment by autc04** [comment]
Yes, 24-bit was dead long before the PowerPC came along, so all PowerPC programs are definitely 32-bit compatible.

I don't think it's even easy to make it a launch-time switch - the first attempt will be a compile time thing. 

The `SYN68K_TO_US` macro (defined in `syn68k_public.h`) is the central point for translating addresses, this is where it should be done. Unfortunately, adding an extra "if" there will already slow things down considerably.

**Comment by Godzil** [comment]
How does Apple cope with that on a 32bit clean system?

**Comment by autc04** [comment]
@Godzil, cope with what exactly?

They didn't have the `SYN68K_TO_US` problem, because the processor does that, and they just didn't support 24-bit mode on later systems.
