### ISSUE TITLE
question: is there way to install extensions like quicktime?

### ISSUE THREAD

**Issue by Randrianasulu** [autc04/executor#52]
I tried qucktime 4  installer but it was tying to write to / , and old Windows version of Executor was not working too, complaining about System Folder.

Manual copying of folders from Basilisk2 disk from inside Executor also not worked

**Comment by autc04** [comment]
No, that will *never* work.
Extensions usually hack into undocumented parts of MacOS, and Executor never even attempted to emulate those. Apple-created extensions like QuickTime are probably even worse - they were created by Apple with full knowledge of undocumented details of the system...
