### ISSUE TITLE
Several Apps don't work (Claris Works 3, MacWrite Pro 1.5)

### ISSUE THREAD

**Issue by codeandcreate** [autc04/executor#7]
These Apps work in original Executor without a problem. i copied them on normal file system (%Claris Works 3.0) and wanted to run them from command line like on the original executor 2:

./executor.app/Contents/MacOS/executor -sticky -memory 128M -keyboard Deutsch -system 7 -nobrowser ./Office/MacWrite\ Pro\ 1.5/MacWrite\ Pro

<img width="429" alt="bildschirmfoto 2019-02-13 um 14 09 37" src="https://user-images.githubusercontent.com/22428204/52714319-79b24380-2f91-11e9-836d-6643b5b6667f.png">

Host: macOS 10.14.1

**Comment by autc04** [comment]
Confirmed for ClarisWorks.

Does MacWrite Pro show the same error message? (If no, I'll move that to a different issue)

**Comment by codeandcreate** [comment]
ClarisWorks 3 works now, thanks!
But still there are some Problems with values and MacWrite Pro seams to have other problems. i'll do two new issues.
