### ISSUE TITLE
ClarisWorks 3 / Lotus 1-2-3: Problem with field checks (numeric)

### ISSUE THREAD

**Issue by codeandcreate** [autc04/executor#8]
If i open the preferences of both apps and want to make changes there are always an error on settings that depends on numeric values.
In the case of CW 3 it's for example "Starting Footnote #".
In the case of Lotus 1-2-3 it's "Column with".

It doesn't matter what is entered in this fields.

![bildschirmfoto_2019-02-17_16-35-07](https://user-images.githubusercontent.com/22428204/52915344-2878bb80-32d3-11e9-8d87-edf4ce5b7370.png)
![bildschirmfoto_2019-02-17_16-35-23](https://user-images.githubusercontent.com/22428204/52915346-2a427f00-32d3-11e9-9caf-99bc2de5734e.png)
![bildschirmfoto_2019-02-17_16-38-53](https://user-images.githubusercontent.com/22428204/52915348-2c0c4280-32d3-11e9-8c1f-4ba263e0ccd9.png)

**Comment by autc04** [comment]
There are apparently some bits of code missing in the floating point implementation for 64 bit platforms. Stay tuned.
